// ============================================================================
// gnss_metric_ref.cpp  --  GOLDEN reference model (single source of truth)
// ----------------------------------------------------------------------------
// Author : John Bagshaw   License : MIT (c) 2026 John Bagshaw
//
// This is the readable, fixed-point-faithful golden model. Every metric in
// Section 3 of the project spec is implemented here in clear integer C++.
//
//   * The HLS kernel (gnss_metric_hls.cpp) is checked TIGHT against this model.
//   * The Python vector generator's mix+PRN front-end is checked against the
//     front-end here (gnss_build_tapped_window) by run_reference_sim.py.
//   * The SystemVerilog behavioral model mirrors this math.
//
// If any of the four implementations disagree, THIS MODEL WINS.
//
// Build modes:
//   g++ -DGNSS_NATIVE_TYPES -DGNSS_REF_MAIN ...  -> standalone gnss_ref_sim exe
//   (also compiled without GNSS_REF_MAIN and linked into the HLS C testbench)
//
// No floating point in the metric/front-end math. Float appears only in the
// optional debug path (not used by the synthesizable equivalents).
// ============================================================================
#include "gnss_config.hpp"
#include "fixed_types.hpp"
#include "gnss_types.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vector>

// ---------------------------------------------------------------------------
// Deterministic 64-entry Q14 sine LUT (amplitude 2^14). Identical values are
// hardcoded in the Python generator and in rtl/gnss/nco_mixer.sv.
// Generated by: round(16384 * sin(2*pi*k/64)) for k in 0..63.
// ---------------------------------------------------------------------------
static const sin_lut_t NCO_SIN_LUT[NCO_LUT_SIZE] = {
       0,   1606,   3196,   4756,   6270,   7723,   9102,  10394,
   11585,  12665,  13623,  14449,  15137,  15679,  16069,  16305,
   16384,  16305,  16069,  15679,  15137,  14449,  13623,  12665,
   11585,  10394,   9102,   7723,   6270,   4756,   3196,   1606,
       0,  -1606,  -3196,  -4756,  -6270,  -7723,  -9102, -10394,
  -11585, -12665, -13623, -14449, -15137, -15679, -16069, -16305,
  -16384, -16305, -16069, -15679, -15137, -14449, -13623, -12665,
  -11585, -10394,  -9102,  -7723,  -6270,  -4756,  -3196,  -1606
};

// ---------------------------------------------------------------------------
// PRN LFSR : 10-bit Fibonacci, x^10 + x^7 + 1. chip = (state&1) ? +1 : -1.
// Reset to seed at each window start; advances once per sample.
// ---------------------------------------------------------------------------
struct LfsrState { unsigned state; };

static inline int lfsr_chip(const LfsrState &s) {
    return (s.state & 1u) ? +1 : -1;
}
static inline void lfsr_advance(LfsrState &s) {
    unsigned fb = ((s.state >> PRN_TAP_A) ^ (s.state >> PRN_TAP_B)) & 1u;
    s.state = ((s.state << 1) | fb) & (unsigned)PRN_LFSR_MASK;
}

// ---------------------------------------------------------------------------
// Front-end: raw I/Q window -> tapped-stream beats (mix + PRN + E/P/L taps).
// Mirrors the spec mixer formula exactly:
//   mixed_I = sat16((I*cos - Q*sin) >> NCO_SCALE)
//   mixed_Q = sat16((I*sin + Q*cos) >> NCO_SCALE)
//   cos = LUT[(idx + QUARTER) % SIZE], sin = LUT[idx], idx = (phase>>SHIFT)%SIZE
// phase and the LFSR both reset at window start (window independence).
// E/P/L taps use the window-local wrap definition:
//   prompt = c[n], early = c[(n+1)%N], late = c[(n-1)%N].
// ---------------------------------------------------------------------------
static void gnss_build_tapped_window(const int16_t *raw_i, const int16_t *raw_q,
                                     int n, int phase_inc, unsigned prn_seed,
                                     std::vector<tapped_beat_t> &out) {
    std::vector<int> chips(n);
    std::vector<int16_t> mix_i(n), mix_q(n);

    LfsrState lf; lf.state = prn_seed & (unsigned)PRN_LFSR_MASK;
    if (lf.state == 0) lf.state = (unsigned)PRN_SEED_DEFAULT;

    unsigned phase = 0;
    for (int k = 0; k < n; ++k) {
        chips[k] = lfsr_chip(lf);
        lfsr_advance(lf);

        int idx_sin = (int)((phase >> NCO_PHASE_SHIFT) & (unsigned)(NCO_LUT_SIZE - 1));
        int idx_cos = (idx_sin + NCO_QUARTER) & (NCO_LUT_SIZE - 1);
        int64_t s = NCO_SIN_LUT[idx_sin];
        int64_t c = NCO_SIN_LUT[idx_cos];

        int64_t I = raw_i[k];
        int64_t Q = raw_q[k];
        mix_i[k] = (int16_t)gnss_sat16((I * c - Q * s) >> NCO_SCALE);
        mix_q[k] = (int16_t)gnss_sat16((I * s + Q * c) >> NCO_SCALE);

        phase = (phase + (unsigned)phase_inc) & ((1u << NCO_PHASE_ACC_BITS) - 1u);
    }

    out.resize(n);
    for (int k = 0; k < n; ++k) {
        tapped_beat_t b;
        b.mixed_i      = mix_i[k];
        b.mixed_q      = mix_q[k];
        b.chip_p       = chips[k];
        b.chip_e       = chips[(k + 1) % n];
        b.chip_l       = chips[(k - 1 + n) % n];
        b.sample_index = k;
        b.last         = (k == n - 1) ? 1 : 0;
        out[k] = b;
    }
}

// ---------------------------------------------------------------------------
// Metric engine: tapped beats for one window -> metrics packet.
// power_prev / noise_prev are passed IN (no hidden static); the current power
// and noise are returned for the caller to latch for the next window.
// ---------------------------------------------------------------------------
static void gnss_compute_metrics_ref(const std::vector<tapped_beat_t> &beats,
                                     uint32_t window_id, uint64_t power_prev,
                                     uint32_t noise_prev, gnss_metrics_t &out) {
    const int n = (int)beats.size();

    // --- power, sub-block means, correlations, doppler ---------------------
    uint64_t power_estimate = 0;
    uint64_t blk_sum[NUM_SUBBLOCKS]; for (int b = 0; b < NUM_SUBBLOCKS; ++b) blk_sum[b] = 0;

    int64_t IcorrE = 0, QcorrE = 0;
    int64_t IcorrP = 0, QcorrP = 0;
    int64_t IcorrL = 0, QcorrL = 0;
    int64_t doppler = 0;
    int64_t prev_i = 0, prev_q = 0; // x[-1] = 0

    for (int k = 0; k < n; ++k) {
        int64_t mi = beats[k].mixed_i;
        int64_t mq = beats[k].mixed_q;

        uint64_t p = (uint64_t)(mi * mi + mq * mq);
        power_estimate += p;

        int blk = k >> SUBBLOCK_LOG2;
        if (blk >= NUM_SUBBLOCKS) blk = NUM_SUBBLOCKS - 1;
        blk_sum[blk] += p;

        IcorrE += mi * beats[k].chip_e;  QcorrE += mq * beats[k].chip_e;
        IcorrP += mi * beats[k].chip_p;  QcorrP += mq * beats[k].chip_p;
        IcorrL += mi * beats[k].chip_l;  QcorrL += mq * beats[k].chip_l;

        // imag(x[n] * conj(x[n-1])) = mq*prev_i - mi*prev_q
        int64_t cross = mq * prev_i - mi * prev_q;
        doppler += (cross < 0) ? -cross : cross;
        prev_i = mi; prev_q = mq;
    }

    // --- noise estimate : smoothed min-of-sub-block-mean -------------------
    uint64_t blk_min = ~0ull;
    for (int b = 0; b < NUM_SUBBLOCKS; ++b) {
        uint64_t mean = blk_sum[b] >> SUBBLOCK_LOG2;
        if (mean < blk_min) blk_min = mean;
    }
    uint32_t noise_estimate;
    if (noise_prev == 0) {
        noise_estimate = (uint32_t)blk_min;          // seed the IIR on first window
    } else {
        int64_t diff = (int64_t)blk_min - (int64_t)noise_prev;
        noise_estimate = (uint32_t)((int64_t)noise_prev + (diff >> NOISE_SMOOTH_SHIFT));
    }

    // --- correlation magnitudes (|I| + |Q| proxy) --------------------------
    uint32_t corr_early  = (uint32_t)((IcorrE < 0 ? -IcorrE : IcorrE) + (QcorrE < 0 ? -QcorrE : QcorrE));
    uint32_t corr_prompt = (uint32_t)((IcorrP < 0 ? -IcorrP : IcorrP) + (QcorrP < 0 ? -QcorrP : QcorrP));
    uint32_t corr_late   = (uint32_t)((IcorrL < 0 ? -IcorrL : IcorrL) + (QcorrL < 0 ? -QcorrL : QcorrL));

    uint32_t symmetry_error = (corr_early > corr_late) ? (corr_early - corr_late)
                                                       : (corr_late - corr_early);

    // --- derived anomaly signals ------------------------------------------
    uint64_t power_jump = (power_estimate > power_prev) ? (power_estimate - power_prev)
                                                        : (power_prev - power_estimate);

    int cn0_proxy = (int)gnss_clamp(
        (int64_t)CN0_K * ((int64_t)gnss_log2_fx(corr_prompt) - (int64_t)gnss_log2_fx(noise_estimate))
            + CN0_OFFSET, 0, CN0_MAX);
    int cn0_abnormal = (int)gnss_clamp((int64_t)CN0_HEALTHY_REF - cn0_proxy, 0, CN0_ABNORMAL_MAX);

    int64_t replica_sig = (int64_t)corr_early + (int64_t)corr_late - (int64_t)corr_prompt;
    if (replica_sig < 0) replica_sig = 0;

    int64_t corr_collapse = (int64_t)CORR_PROMPT_REF - (int64_t)corr_prompt;
    if (corr_collapse < 0) corr_collapse = 0;

    // tone / wideband signature: the elevated noise floor. Under both tone and
    // wideband jamming every sub-block mean is lifted, so the robust low-
    // percentile noise estimate rises far above the nominal thermal floor.
    int64_t tone_metric = (int64_t)noise_estimate;

    // --- normalized terms --------------------------------------------------
    int nSym  = gnss_norm(symmetry_error, SYM_NORM_SHIFT, NORM_MAX);
    int nDop  = gnss_norm((int64_t)doppler, DOPP_NORM_SHIFT, NORM_MAX);
    int nCn0  = gnss_norm(cn0_abnormal, CN0ABN_NORM_SHIFT, NORM_MAX);
    int nRepl = gnss_norm(replica_sig, REPL_NORM_SHIFT, NORM_MAX);
    int nPwr  = gnss_norm((int64_t)power_estimate, PWR_NORM_SHIFT, NORM_MAX);
    int nCol  = gnss_norm(corr_collapse, COLLAPSE_NORM_SHIFT, NORM_MAX);
    int nTone = gnss_norm(tone_metric, TONE_NORM_SHIFT, NORM_MAX);

    int64_t spoof = (int64_t)W_SYM * nSym + (int64_t)W_DOP * nDop
                  + (int64_t)W_CN0 * nCn0 + (int64_t)W_REPL * nRepl;
    int64_t jam   = (int64_t)W_PWR * nPwr + (int64_t)W_LOWCN0 * nCn0
                  + (int64_t)W_COLLAPSE * nCol + (int64_t)W_TONE * nTone;
    uint32_t spoof_score = (uint32_t)gnss_clamp(spoof, 0, SCORE_MAX);
    uint32_t jam_score   = (uint32_t)gnss_clamp(jam,   0, SCORE_MAX);

    // --- alert flags -------------------------------------------------------
    uint32_t flags = 0;
    if (power_estimate > (uint64_t)POWER_JAM_THRESHOLD) flags |= (1u << FLAG_HIGH_POWER_JAM);
    if (cn0_proxy < CN0_DROP_THRESHOLD)                 flags |= (1u << FLAG_CN0_DROP);
    if (symmetry_error > (uint32_t)SYMMETRY_THRESHOLD)  flags |= (1u << FLAG_CORR_ASYMMETRY);
    if ((uint64_t)doppler > (uint64_t)DOPPLER_ENERGY_THRESHOLD) flags |= (1u << FLAG_DOPPLER_ANOMALY);
    if (spoof_score > (uint32_t)SPOOF_SCORE_THRESHOLD)  flags |= (1u << FLAG_SPOOF_SCORE_HIGH);
    if (jam_score > (uint32_t)JAM_SCORE_THRESHOLD)      flags |= (1u << FLAG_JAM_SCORE_HIGH);
    uint32_t sample_count = (uint32_t)n;
    uint32_t packet_status = PKT_STATUS_OK;
    if (sample_count != (uint32_t)WINDOW_SIZE) {
        flags |= (1u << FLAG_MALFORMED_PACKET);
        packet_status = PKT_STATUS_MALFORMED;
    }

    // --- pack packet -------------------------------------------------------
    out.window_id        = window_id;
    out.power_estimate   = power_estimate;
    out.noise_estimate   = noise_estimate;
    out.cn0_proxy        = (uint32_t)cn0_proxy;
    out.corr_prompt      = corr_prompt;
    out.corr_early       = corr_early;
    out.corr_late        = corr_late;
    out.symmetry_error   = symmetry_error;
    out.doppler_energy   = (uint64_t)doppler;
    out.power_jump_metric = power_jump;
    out.spoof_score      = spoof_score;
    out.jam_score        = jam_score;
    out.alert_flags      = flags;
    // Software model latency estimate: ingestion + fixed pipeline depth.
    // Real cycle-accurate latency comes from axis_latency_counter in XSim.
    out.latency_cycles   = sample_count + 8;
    out.sample_count     = sample_count;
    out.packet_status    = packet_status;
}

// Expose the two stages for the HLS testbench (declared extern "C"-free; the
// tb includes this .cpp directly to share the exact golden math).
void ref_build_tapped_window(const int16_t *raw_i, const int16_t *raw_q, int n,
                             int phase_inc, unsigned prn_seed,
                             std::vector<tapped_beat_t> &out) {
    gnss_build_tapped_window(raw_i, raw_q, n, phase_inc, prn_seed, out);
}
void ref_compute_metrics(const std::vector<tapped_beat_t> &beats,
                         uint32_t window_id, uint64_t power_prev,
                         uint32_t noise_prev, gnss_metrics_t &out) {
    gnss_compute_metrics_ref(beats, window_id, power_prev, noise_prev, out);
}

// ===========================================================================
// Standalone golden simulator : gnss_ref_sim <scenario_dir> <out_file>
//   reads <scenario_dir>/input_iq.txt   (sample_index i q tlast)
//   computes metrics window-by-window (carrying power_prev / noise_prev)
//   writes <out_file> as key=value lines (per window, blank-line separated)
//   ALSO cross-checks <scenario_dir>/tapped_stream.txt against the front-end
//   here (validates the Python generator's mix+PRN matches the golden model).
// ===========================================================================
#ifdef GNSS_REF_MAIN

static int load_iq(const char *path, std::vector<int16_t> &I,
                   std::vector<int16_t> &Q, std::vector<int> &LAST) {
    FILE *f = fopen(path, "r");
    if (!f) { fprintf(stderr, "ERROR: cannot open %s\n", path); return -1; }
    int idx, iv, qv, last;
    while (fscanf(f, "%d %d %d %d", &idx, &iv, &qv, &last) == 4) {
        I.push_back((int16_t)iv); Q.push_back((int16_t)qv); LAST.push_back(last);
    }
    fclose(f);
    return 0;
}

// Returns number of mismatched beats (0 = Python front-end matches golden).
static long crosscheck_tapped(const char *path,
                              const std::vector<tapped_beat_t> &beats,
                              int win_base) {
    FILE *f = fopen(path, "r");
    if (!f) return -1; // missing file is non-fatal; caller decides
    // tapped_stream.txt line: window sample_index mixed_i mixed_q chip_e chip_p chip_l last
    long mism = 0; int w, s, mi, mq, ce, cp, cl, lb;
    // skip header lines starting with '#'
    char line[256];
    long gi = win_base;
    while (fgets(line, sizeof(line), f)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        if (sscanf(line, "%d %d %d %d %d %d %d %d", &w, &s, &mi, &mq, &ce, &cp, &cl, &lb) != 8) continue;
        if (gi < 0 || gi >= (long)beats.size()) { gi++; continue; }
        const tapped_beat_t &b = beats[gi];
        if (b.mixed_i != mi || b.mixed_q != mq || b.chip_e != ce ||
            b.chip_p != cp || b.chip_l != cl) mism++;
        gi++;
    }
    fclose(f);
    return mism;
}

static void emit_metrics(FILE *o, const gnss_metrics_t &m) {
    fprintf(o, "window_id=%u\n",         m.window_id);
    fprintf(o, "power_estimate=%llu\n",  (unsigned long long)m.power_estimate);
    fprintf(o, "noise_estimate=%u\n",    m.noise_estimate);
    fprintf(o, "cn0_proxy=%u\n",         m.cn0_proxy);
    fprintf(o, "corr_prompt=%u\n",       m.corr_prompt);
    fprintf(o, "corr_early=%u\n",        m.corr_early);
    fprintf(o, "corr_late=%u\n",         m.corr_late);
    fprintf(o, "symmetry_error=%u\n",    m.symmetry_error);
    fprintf(o, "doppler_energy=%llu\n",  (unsigned long long)m.doppler_energy);
    fprintf(o, "power_jump_metric=%llu\n", (unsigned long long)m.power_jump_metric);
    fprintf(o, "spoof_score=%u\n",       m.spoof_score);
    fprintf(o, "jam_score=%u\n",         m.jam_score);
    fprintf(o, "alert_flags=%u\n",       m.alert_flags);
    fprintf(o, "latency_cycles=%u\n",    m.latency_cycles);
    fprintf(o, "sample_count=%u\n",      m.sample_count);
    fprintf(o, "packet_status=%u\n",     m.packet_status);
    fprintf(o, "\n");
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: %s <scenario_dir> <out_file>\n", argv[0]);
        return 2;
    }
    char iq_path[512], tap_path[512];
    snprintf(iq_path, sizeof(iq_path), "%s/input_iq.txt", argv[1]);
    snprintf(tap_path, sizeof(tap_path), "%s/tapped_stream.txt", argv[1]);

    std::vector<int16_t> I, Q; std::vector<int> LAST;
    if (load_iq(iq_path, I, Q, LAST) != 0) return 1;
    const int N = WINDOW_SIZE;
    if ((int)I.size() < N) { fprintf(stderr, "ERROR: too few samples\n"); return 1; }

    FILE *o = fopen(argv[2], "w");
    if (!o) { fprintf(stderr, "ERROR: cannot write %s\n", argv[2]); return 1; }

    uint64_t power_prev = 0; uint32_t noise_prev = 0;
    long total_mismatch = 0; int crosscheck_seen = 0;
    int num_windows = (int)I.size() / N;
    for (int w = 0; w < num_windows; ++w) {
        std::vector<int16_t> wi(I.begin() + (long)w * N, I.begin() + (long)(w + 1) * N);
        std::vector<int16_t> wq(Q.begin() + (long)w * N, Q.begin() + (long)(w + 1) * N);
        std::vector<tapped_beat_t> beats;
        gnss_build_tapped_window(wi.data(), wq.data(), N,
                                 NCO_PHASE_INC_DEFAULT, PRN_SEED_DEFAULT, beats);

        long mism = crosscheck_tapped(tap_path, beats, w * N);
        if (mism >= 0) { crosscheck_seen = 1; total_mismatch += mism; }

        gnss_metrics_t m;
        gnss_compute_metrics_ref(beats, (uint32_t)w, power_prev, noise_prev, m);
        emit_metrics(o, m);
        power_prev = m.power_estimate;
        noise_prev = m.noise_estimate;
    }
    fclose(o);

    if (crosscheck_seen) {
        if (total_mismatch == 0) {
            fprintf(stderr, "[ref] %s: front-end crosscheck OK (%d windows)\n",
                    argv[1], num_windows);
        } else {
            fprintf(stderr, "[ref] %s: FRONT-END MISMATCH on %ld beats\n",
                    argv[1], total_mismatch);
            return 3; // Python front-end disagrees with the golden model
        }
    }
    return 0;
}
#endif // GNSS_REF_MAIN
