#!/usr/bin/env python3
"""gnss_cfg.py -- parse hls/include/gnss_config.hpp into a Python dict.

This keeps the SINGLE SOURCE OF TRUTH in the C/HLS header. The Python vector
generator and golden-sim cross-check read their constants from here so they can
never silently drift from the kernel.

Author: John Bagshaw   License: MIT (c) 2026 John Bagshaw
"""
import os
import re

_THIS = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_THIS)
CONFIG_HPP = os.path.join(_REPO, "hls", "include", "gnss_config.hpp")

# Matches:  static const <int-type> NAME = VALUE;   (integer literal only)
_PAT = re.compile(
    r"static\s+const\s+(?:int|unsigned|long|int32_t|uint32_t|int64_t)\s+"
    r"(\w+)\s*=\s*(-?\d+)\s*;"
)


def load_config(path=CONFIG_HPP):
    """Return {NAME: int} parsed from gnss_config.hpp."""
    cfg = {}
    with open(path, "r") as f:
        for line in f:
            m = _PAT.search(line)
            if m:
                cfg[m.group(1)] = int(m.group(2))
    if "WINDOW_SIZE" not in cfg:
        raise RuntimeError("failed to parse gnss_config.hpp (no WINDOW_SIZE)")
    return cfg


# Deterministic 64-entry Q14 sine LUT. MUST equal NCO_SIN_LUT in
# gnss_metric_ref.cpp and the ROM in rtl/gnss/nco_mixer.sv.
# Generated by round(16384*sin(2*pi*k/64)) for k in 0..63.
NCO_SIN_LUT = [
    0, 1606, 3196, 4756, 6270, 7723, 9102, 10394,
    11585, 12665, 13623, 14449, 15137, 15679, 16069, 16305,
    16384, 16305, 16069, 15679, 15137, 14449, 13623, 12665,
    11585, 10394, 9102, 7723, 6270, 4756, 3196, 1606,
    0, -1606, -3196, -4756, -6270, -7723, -9102, -10394,
    -11585, -12665, -13623, -14449, -15137, -15679, -16069, -16305,
    -16384, -16305, -16069, -15679, -15137, -14449, -13623, -12665,
    -11585, -10394, -9102, -7723, -6270, -4756, -3196, -1606,
]


if __name__ == "__main__":
    cfg = load_config()
    for k in sorted(cfg):
        print(f"{k} = {cfg[k]}")
